//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50215.44.
// 
namespace Commanigy.Iquomi.Services.IqAlerts {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts", IsNullable=false)]
    public partial class IqAlerts : IqAlertsType {
        
        private string changeNumberField;
        
        private string instanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string InstanceId {
            get {
                return this.instanceIdField;
            }
            set {
                this.instanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class IqAlertsType {
        
        private StreamType[] streamField;
        
        private ConnectionType[] connectionField;
        
        private SubscriptionType[] subscriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stream")]
        public StreamType[] Stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Connection")]
        public ConnectionType[] Connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subscription")]
        public SubscriptionType[] Subscription {
            get {
                return this.subscriptionField;
            }
            set {
                this.subscriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class StreamType {
        
        private StreamClassType classField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private StreamPositionType positionField;
        
        private NotificationQueryType argotQueryField;
        
        private bool argotQueryFieldSpecified;
        
        private ArgotType[] argotField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public StreamClassType Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationSpecified {
            get {
                return this.expirationFieldSpecified;
            }
            set {
                this.expirationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public StreamPositionType Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public NotificationQueryType ArgotQuery {
            get {
                return this.argotQueryField;
            }
            set {
                this.argotQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArgotQuerySpecified {
            get {
                return this.argotQueryFieldSpecified;
            }
            set {
                this.argotQueryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Argot")]
        public ArgotType[] Argot {
            get {
                return this.argotField;
            }
            set {
                this.argotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum StreamClassType {
        
        /// <remarks/>
        Buffer,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum StreamPositionType {
        
        /// <remarks/>
        AtFront,
        
        /// <remarks/>
        AtEnd,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum NotificationQueryType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*")]
        Item,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ArgotType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string argotURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ArgotURI {
            get {
                return this.argotURIField;
            }
            set {
                this.argotURIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class RoutingType {
        
        private string timestampField;
        
        private string hopsField;
        
        /// <remarks/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string Hops {
            get {
                return this.hopsField;
            }
            set {
                this.hopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ContentsType {
        
        private ArgotListTypeArgot[] argotField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Argot", IsNullable=false)]
        public ArgotListTypeArgot[] Argot {
            get {
                return this.argotField;
            }
            set {
                this.argotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ArgotListTypeArgot : ArgotType {
        
        private string nameField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ToType {
        
        private string originalUserField;
        
        /// <remarks/>
        public string OriginalUser {
            get {
                return this.originalUserField;
            }
            set {
                this.originalUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class CategoryType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ExpiresType {
        
        private string ttlField;
        
        private string onDateField;
        
        private string replaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OnDate {
            get {
                return this.onDateField;
            }
            set {
                this.onDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class IdentityHeaderType {
        
        private string onBehalfOfUserField;
        
        private string licenseHolderField;
        
        private string platformIdField;
        
        private string typeField;
        
        /// <remarks/>
        public string OnBehalfOfUser {
            get {
                return this.onBehalfOfUserField;
            }
            set {
                this.onBehalfOfUserField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseHolder {
            get {
                return this.licenseHolderField;
            }
            set {
                this.licenseHolderField = value;
            }
        }
        
        /// <remarks/>
        public string PlatformId {
            get {
                return this.platformIdField;
            }
            set {
                this.platformIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class FromType {
        
        private IdentityHeaderType identityHeaderField;
        
        private ExpiresType expiresAtField;
        
        private string acknowledgeField;
        
        private CategoryType categoryField;
        
        /// <remarks/>
        public IdentityHeaderType IdentityHeader {
            get {
                return this.identityHeaderField;
            }
            set {
                this.identityHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ExpiresType ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        public string Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public CategoryType Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class NotificationType {
        
        private FromType fromField;
        
        private ToType toField;
        
        private ContentsType contentsField;
        
        private RoutingType routingField;
        
        private string idField;
        
        /// <remarks/>
        public FromType From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public ToType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public ContentsType Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        public RoutingType Routing {
            get {
                return this.routingField;
            }
            set {
                this.routingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionType {
        
        private SubscriptionTypeTrigger triggerField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private SubscriptionTypeContext contextField;
        
        private string toField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public SubscriptionTypeTrigger Trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionTypeContext Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeTrigger {
        
        private string selectField;
        
        private SubscriptionTypeTriggerMode modeField;
        
        private string baseChangeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Select {
            get {
                return this.selectField;
            }
            set {
                this.selectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public SubscriptionTypeTriggerMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string BaseChangeNumber {
            get {
                return this.baseChangeNumberField;
            }
            set {
                this.baseChangeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public enum SubscriptionTypeTriggerMode {
        
        /// <remarks/>
        IncludeData,
        
        /// <remarks/>
        ExcludeData,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeContext {
        
        private System.Xml.XmlElement[] anyField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ConnectionType {
        
        private ConnectionClassType classField;
        
        private ConnectionStatusType statusField;
        
        private ConnectionCharacteristicsType characteristicsField;
        
        private System.DateTime expirationField;
        
        private NotificationQueryType argotQueryField;
        
        private ArgotType[] argotField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public ConnectionClassType Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionStatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionCharacteristicsType Characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        public NotificationQueryType ArgotQuery {
            get {
                return this.argotQueryField;
            }
            set {
                this.argotQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Argot")]
        public ArgotType[] Argot {
            get {
                return this.argotField;
            }
            set {
                this.argotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum ConnectionClassType {
        
        /// <remarks/>
        Push_http,
        
        /// <remarks/>
        Pull_http,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum ConnectionStatusType {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Busy,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public enum ConnectionCharacteristicsType {
        
        /// <remarks/>
        Reliable,
        
        /// <remarks/>
        Unreliable,
        
        /// <remarks/>
        ConnectionPoll,
        
        /// <remarks/>
        UserAgentPoll,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts", IsNullable=false)]
    public partial class HumanReadable {
        
        private string baseUrlField;
        
        private string actionUrlField;
        
        private string subscriptionUrlField;
        
        private HumanReadableLanguage[] languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string BaseUrl {
            get {
                return this.baseUrlField;
            }
            set {
                this.baseUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ActionUrl {
            get {
                return this.actionUrlField;
            }
            set {
                this.actionUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string SubscriptionUrl {
            get {
                return this.subscriptionUrlField;
            }
            set {
                this.subscriptionUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Language")]
        public HumanReadableLanguage[] Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class HumanReadableLanguage {
        
        private string textField;
        
        private string langField;
        
        private string iconUrlField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string IconUrl {
            get {
                return this.iconUrlField;
            }
            set {
                this.iconUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    [System.Xml.Serialization.XmlRootAttribute("NotifyRequest", Namespace="http://schemas.iquomi.com/2004/01/iqAlerts", IsNullable=false)]
    public partial class NotifyRequestType {
        
        private NotificationType[] notificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notification")]
        public NotificationType[] Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
    }
}
