//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50215.44.
// 
namespace Commanigy.Iquomi.Client.SmartDevice.AdminRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IquomiWSAdminSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageItem[]))]
    public partial class IquomiWSAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SoapAuthenticationType soapAuthenticationTypeValueField;
        
        /// <remarks/>
        public IquomiWSAdmin() {
            this.Url = "http://localhost:4081/webservices/IquomiWSAdmin.asmx";
        }
        
        public SoapAuthenticationType SoapAuthenticationTypeValue {
            get {
                return this.soapAuthenticationTypeValueField;
            }
            set {
                this.soapAuthenticationTypeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthenticationTypeValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscriptionServices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Service[] GetSubscriptionServices() {
            object[] results = this.Invoke("GetSubscriptionServices", new object[0]);
            return ((Service[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSubscriptionServices(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSubscriptionServices", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Service[] EndGetSubscriptionServices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Service[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthenticationTypeValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadLatestPackage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Package DownloadLatestPackage(string serviceName, string platform) {
            object[] results = this.Invoke("DownloadLatestPackage", new object[] {
                        serviceName,
                        platform});
            return ((Package)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDownloadLatestPackage(string serviceName, string platform, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DownloadLatestPackage", new object[] {
                        serviceName,
                        platform}, callback, asyncState);
        }
        
        /// <remarks/>
        public Package EndDownloadLatestPackage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Package)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class SoapAuthenticationType : System.Web.Services.Protocols.SoapHeader {
        
        private string iqidField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Iqid {
            get {
                return this.iqidField;
            }
            set {
                this.iqidField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PackageItem {
        
        private int idField;
        
        private int packageIdField;
        
        private string nameField;
        
        private string typeField;
        
        private int sizeField;
        
        private object dataField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Package {
        
        private int idField;
        
        private int serviceIdField;
        
        private string versionField;
        
        private System.DateTime releaseDateField;
        
        private string stateField;
        
        private PackageItem[] itemsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReleaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public PackageItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Service {
        
        private int idField;
        
        private int authorIdField;
        
        private string nameField;
        
        private string versionField;
        
        private string xsdField;
        
        private string urlXsdField;
        
        private string urlIconField;
        
        private string urlHomepageField;
        
        private string stateField;
        
        private string roleMapField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int AuthorId {
            get {
                return this.authorIdField;
            }
            set {
                this.authorIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Xsd {
            get {
                return this.xsdField;
            }
            set {
                this.xsdField = value;
            }
        }
        
        /// <remarks/>
        public string UrlXsd {
            get {
                return this.urlXsdField;
            }
            set {
                this.urlXsdField = value;
            }
        }
        
        /// <remarks/>
        public string UrlIcon {
            get {
                return this.urlIconField;
            }
            set {
                this.urlIconField = value;
            }
        }
        
        /// <remarks/>
        public string UrlHomepage {
            get {
                return this.urlHomepageField;
            }
            set {
                this.urlHomepageField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string RoleMap {
            get {
                return this.roleMapField;
            }
            set {
                this.roleMapField = value;
            }
        }
    }
}
