//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50215.44.
// 
namespace Commanigy.Iquomi.Services.IqCalendar {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar", IsNullable=false)]
    public partial class IqCalendar : IqCalendarType {
        
        private string changeNumberField;
        
        private string instanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string InstanceId {
            get {
                return this.instanceIdField;
            }
            set {
                this.instanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class IqCalendarType {
        
        private EventType[] eventField;
        
        private SubscriptionType[] subscriptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public EventType[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subscription")]
        public SubscriptionType[] Subscription {
            get {
                return this.subscriptionField;
            }
            set {
                this.subscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class EventType {
        
        private BodyType bodyField;
        
        private AttendeeEventExtraBlueType attendeeEventExtraField;
        
        private AttachmentMetadataBlueType[] attachmentField;
        
        private ReminderBlueType reminderField;
        
        private AttendeeBlueType[] attendeeField;
        
        private RecurrenceType recurrenceField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        private CalendarLocaleEnum calendarTypeField;
        
        private bool calendarTypeFieldSpecified;
        
        private int advanceHijriValueField;
        
        private bool advanceHijriValueFieldSpecified;
        
        /// <remarks/>
        public BodyType Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public AttendeeEventExtraBlueType AttendeeEventExtra {
            get {
                return this.attendeeEventExtraField;
            }
            set {
                this.attendeeEventExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment")]
        public AttachmentMetadataBlueType[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        public ReminderBlueType Reminder {
            get {
                return this.reminderField;
            }
            set {
                this.reminderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attendee")]
        public AttendeeBlueType[] Attendee {
            get {
                return this.attendeeField;
            }
            set {
                this.attendeeField = value;
            }
        }
        
        /// <remarks/>
        public RecurrenceType Recurrence {
            get {
                return this.recurrenceField;
            }
            set {
                this.recurrenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CalendarLocaleEnum CalendarType {
            get {
                return this.calendarTypeField;
            }
            set {
                this.calendarTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalendarTypeSpecified {
            get {
                return this.calendarTypeFieldSpecified;
            }
            set {
                this.calendarTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AdvanceHijriValue {
            get {
                return this.advanceHijriValueField;
            }
            set {
                this.advanceHijriValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvanceHijriValueSpecified {
            get {
                return this.advanceHijriValueFieldSpecified;
            }
            set {
                this.advanceHijriValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class BodyType {
        
        private CatType[] catField;
        
        private LocalizableString titleField;
        
        private LongText fullDescriptionField;
        
        private LocalizableString locationField;
        
        private MeetingStatusEnum meetingStatusField;
        
        private bool meetingStatusFieldSpecified;
        
        private System.DateTime recurrenceIdField;
        
        private bool recurrenceIdFieldSpecified;
        
        private System.DateTime lastUpdateTimeField;
        
        private bool lastUpdateTimeFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private bool allDayField;
        
        private bool allDayFieldSpecified;
        
        private bool floatingField;
        
        private bool floatingFieldSpecified;
        
        private int travelTimeToField;
        
        private bool travelTimeToFieldSpecified;
        
        private int travelTimeFromField;
        
        private bool travelTimeFromFieldSpecified;
        
        private FreeBusyStatusType freeBusyStatusField;
        
        private bool freeBusyStatusFieldSpecified;
        
        private string cuidField;
        
        private UserReference organizerField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string changeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cat")]
        public CatType[] Cat {
            get {
                return this.catField;
            }
            set {
                this.catField = value;
            }
        }
        
        /// <remarks/>
        public LocalizableString Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public LongText FullDescription {
            get {
                return this.fullDescriptionField;
            }
            set {
                this.fullDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public LocalizableString Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public MeetingStatusEnum MeetingStatus {
            get {
                return this.meetingStatusField;
            }
            set {
                this.meetingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeetingStatusSpecified {
            get {
                return this.meetingStatusFieldSpecified;
            }
            set {
                this.meetingStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RecurrenceId {
            get {
                return this.recurrenceIdField;
            }
            set {
                this.recurrenceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurrenceIdSpecified {
            get {
                return this.recurrenceIdFieldSpecified;
            }
            set {
                this.recurrenceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdateTimeSpecified {
            get {
                return this.lastUpdateTimeFieldSpecified;
            }
            set {
                this.lastUpdateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool AllDay {
            get {
                return this.allDayField;
            }
            set {
                this.allDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllDaySpecified {
            get {
                return this.allDayFieldSpecified;
            }
            set {
                this.allDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Floating {
            get {
                return this.floatingField;
            }
            set {
                this.floatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FloatingSpecified {
            get {
                return this.floatingFieldSpecified;
            }
            set {
                this.floatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TravelTimeTo {
            get {
                return this.travelTimeToField;
            }
            set {
                this.travelTimeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelTimeToSpecified {
            get {
                return this.travelTimeToFieldSpecified;
            }
            set {
                this.travelTimeToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TravelTimeFrom {
            get {
                return this.travelTimeFromField;
            }
            set {
                this.travelTimeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelTimeFromSpecified {
            get {
                return this.travelTimeFromFieldSpecified;
            }
            set {
                this.travelTimeFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FreeBusyStatusType FreeBusyStatus {
            get {
                return this.freeBusyStatusField;
            }
            set {
                this.freeBusyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FreeBusyStatusSpecified {
            get {
                return this.freeBusyStatusFieldSpecified;
            }
            set {
                this.freeBusyStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Cuid {
            get {
                return this.cuidField;
            }
            set {
                this.cuidField = value;
            }
        }
        
        /// <remarks/>
        public UserReference Organizer {
            get {
                return this.organizerField;
            }
            set {
                this.organizerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class CatType {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionType {
        
        private SubscriptionTypeTrigger triggerField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private SubscriptionTypeContext contextField;
        
        private string toField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public SubscriptionTypeTrigger Trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionTypeContext Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeTrigger {
        
        private string selectField;
        
        private SubscriptionTypeTriggerMode modeField;
        
        private string baseChangeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Select {
            get {
                return this.selectField;
            }
            set {
                this.selectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public SubscriptionTypeTriggerMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string BaseChangeNumber {
            get {
                return this.baseChangeNumberField;
            }
            set {
                this.baseChangeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public enum SubscriptionTypeTriggerMode {
        
        /// <remarks/>
        IncludeData,
        
        /// <remarks/>
        ExcludeData,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeContext {
        
        private System.Xml.XmlElement[] anyField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class ReminderExceptionType {
        
        private bool setField;
        
        private bool setFieldSpecified;
        
        private int offsetField;
        
        private bool offsetFieldSpecified;
        
        private int interruptabilityField;
        
        private bool interruptabilityFieldSpecified;
        
        /// <remarks/>
        public bool Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetSpecified {
            get {
                return this.setFieldSpecified;
            }
            set {
                this.setFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Interruptability {
            get {
                return this.interruptabilityField;
            }
            set {
                this.interruptabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InterruptabilitySpecified {
            get {
                return this.interruptabilityFieldSpecified;
            }
            set {
                this.interruptabilityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class ModifiedExceptionType {
        
        private System.DateTime recurrenceIdField;
        
        private ModifiedExceptionTypeBody bodyField;
        
        private AttendeeEventExtraType attendeeEventExtraField;
        
        private string[] deletedAttendeeField;
        
        private string[] deletedAttachmentField;
        
        private AttachmentMetadataType[] attachmentField;
        
        private AttendeeType[] attendeeField;
        
        private ReminderExceptionType reminderField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public System.DateTime RecurrenceId {
            get {
                return this.recurrenceIdField;
            }
            set {
                this.recurrenceIdField = value;
            }
        }
        
        /// <remarks/>
        public ModifiedExceptionTypeBody Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public AttendeeEventExtraType AttendeeEventExtra {
            get {
                return this.attendeeEventExtraField;
            }
            set {
                this.attendeeEventExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeletedAttendee")]
        public string[] DeletedAttendee {
            get {
                return this.deletedAttendeeField;
            }
            set {
                this.deletedAttendeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeletedAttachment")]
        public string[] DeletedAttachment {
            get {
                return this.deletedAttachmentField;
            }
            set {
                this.deletedAttachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment")]
        public AttachmentMetadataType[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attendee")]
        public AttendeeType[] Attendee {
            get {
                return this.attendeeField;
            }
            set {
                this.attendeeField = value;
            }
        }
        
        /// <remarks/>
        public ReminderExceptionType Reminder {
            get {
                return this.reminderField;
            }
            set {
                this.reminderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class ModifiedExceptionTypeBody {
        
        private LocalizableString titleField;
        
        private LongText fullDescriptionField;
        
        private LocalizableString locationField;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private System.DateTime endTimeField;
        
        private bool endTimeFieldSpecified;
        
        private bool allDayField;
        
        private bool allDayFieldSpecified;
        
        private int travelTimeToField;
        
        private bool travelTimeToFieldSpecified;
        
        private int travelTimeFromField;
        
        private bool travelTimeFromFieldSpecified;
        
        private FreeBusyStatusType freeBusyStatusField;
        
        private bool freeBusyStatusFieldSpecified;
        
        private UserReference organizerField;
        
        /// <remarks/>
        public LocalizableString Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public LongText FullDescription {
            get {
                return this.fullDescriptionField;
            }
            set {
                this.fullDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public LocalizableString Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeSpecified {
            get {
                return this.endTimeFieldSpecified;
            }
            set {
                this.endTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllDay {
            get {
                return this.allDayField;
            }
            set {
                this.allDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllDaySpecified {
            get {
                return this.allDayFieldSpecified;
            }
            set {
                this.allDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TravelTimeTo {
            get {
                return this.travelTimeToField;
            }
            set {
                this.travelTimeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelTimeToSpecified {
            get {
                return this.travelTimeToFieldSpecified;
            }
            set {
                this.travelTimeToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TravelTimeFrom {
            get {
                return this.travelTimeFromField;
            }
            set {
                this.travelTimeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelTimeFromSpecified {
            get {
                return this.travelTimeFromFieldSpecified;
            }
            set {
                this.travelTimeFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FreeBusyStatusType FreeBusyStatus {
            get {
                return this.freeBusyStatusField;
            }
            set {
                this.freeBusyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FreeBusyStatusSpecified {
            get {
                return this.freeBusyStatusFieldSpecified;
            }
            set {
                this.freeBusyStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public UserReference Organizer {
            get {
                return this.organizerField;
            }
            set {
                this.organizerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class LocalizableString {
        
        private string langField;
        
        private DirType dirField;
        
        private bool dirFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public DirType Dir {
            get {
                return this.dirField;
            }
            set {
                this.dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirSpecified {
            get {
                return this.dirFieldSpecified;
            }
            set {
                this.dirFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public enum DirType {
        
        /// <remarks/>
        Rtl,
        
        /// <remarks/>
        Ltr,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class LongText {
        
        private string langField;
        
        private DirType dirField;
        
        private bool dirFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public DirType Dir {
            get {
                return this.dirField;
            }
            set {
                this.dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirSpecified {
            get {
                return this.dirFieldSpecified;
            }
            set {
                this.dirFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum FreeBusyStatusType {
        
        /// <remarks/>
        Free,
        
        /// <remarks/>
        Busy,
        
        /// <remarks/>
        Tentative,
        
        /// <remarks/>
        Away,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UninviteAttendeeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeBlueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserReferenceCategorized))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class UserReference {
        
        private LocalizableString nameField;
        
        private string puidField;
        
        private string emailField;
        
        /// <remarks/>
        public LocalizableString Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Puid {
            get {
                return this.puidField;
            }
            set {
                this.puidField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class UninviteAttendeeType : UserReference {
        
        private bool deleteAttendeeField;
        
        private bool deleteAttendeeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DeleteAttendee {
            get {
                return this.deleteAttendeeField;
            }
            set {
                this.deleteAttendeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteAttendeeSpecified {
            get {
                return this.deleteAttendeeFieldSpecified;
            }
            set {
                this.deleteAttendeeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeBlueType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttendeeInfoType : UserReference {
        
        private InviteTypeEnum inviteTypeField;
        
        /// <remarks/>
        public InviteTypeEnum InviteType {
            get {
                return this.inviteTypeField;
            }
            set {
                this.inviteTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum InviteTypeEnum {
        
        /// <remarks/>
        Required,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Resource,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeBlueType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttendeeType : AttendeeInfoType {
        
        private System.DateTime responseTimeField;
        
        private bool responseTimeFieldSpecified;
        
        private AttendeeAcceptEnum responseTypeField;
        
        private bool responseTypeFieldSpecified;
        
        private System.DateTime counterProposeStartTimeField;
        
        private bool counterProposeStartTimeFieldSpecified;
        
        private System.DateTime counterProposeEndTimeField;
        
        private bool counterProposeEndTimeFieldSpecified;
        
        private string counterProposeLocationField;
        
        private LongText responseBodyField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public System.DateTime ResponseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseTimeSpecified {
            get {
                return this.responseTimeFieldSpecified;
            }
            set {
                this.responseTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AttendeeAcceptEnum ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseTypeSpecified {
            get {
                return this.responseTypeFieldSpecified;
            }
            set {
                this.responseTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CounterProposeStartTime {
            get {
                return this.counterProposeStartTimeField;
            }
            set {
                this.counterProposeStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CounterProposeStartTimeSpecified {
            get {
                return this.counterProposeStartTimeFieldSpecified;
            }
            set {
                this.counterProposeStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CounterProposeEndTime {
            get {
                return this.counterProposeEndTimeField;
            }
            set {
                this.counterProposeEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CounterProposeEndTimeSpecified {
            get {
                return this.counterProposeEndTimeFieldSpecified;
            }
            set {
                this.counterProposeEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CounterProposeLocation {
            get {
                return this.counterProposeLocationField;
            }
            set {
                this.counterProposeLocationField = value;
            }
        }
        
        /// <remarks/>
        public LongText ResponseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum AttendeeAcceptEnum {
        
        /// <remarks/>
        Accept,
        
        /// <remarks/>
        Decline,
        
        /// <remarks/>
        Tentative,
        
        /// <remarks/>
        CounterPropose,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttendeeBlueType : AttendeeType {
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class UserReferenceCategorized : UserReference {
        
        private CatType catField;
        
        /// <remarks/>
        public CatType Cat {
            get {
                return this.catField;
            }
            set {
                this.catField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttendeeEventExtraBlueType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttendeeEventExtraType {
        
        private FreeBusyStatusType intendedFreeBusyField;
        
        private bool intendedFreeBusyFieldSpecified;
        
        private System.DateTime responseTimeField;
        
        private bool responseTimeFieldSpecified;
        
        private AttendeeAcceptEnum responseTypeField;
        
        private bool responseTypeFieldSpecified;
        
        private System.DateTime counterProposeStartTimeField;
        
        private bool counterProposeStartTimeFieldSpecified;
        
        private System.DateTime counterProposeEndTimeField;
        
        private bool counterProposeEndTimeFieldSpecified;
        
        private string counterProposeLocationField;
        
        private LongText responseBodyField;
        
        private UserReference delegateResponderField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public FreeBusyStatusType IntendedFreeBusy {
            get {
                return this.intendedFreeBusyField;
            }
            set {
                this.intendedFreeBusyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntendedFreeBusySpecified {
            get {
                return this.intendedFreeBusyFieldSpecified;
            }
            set {
                this.intendedFreeBusyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ResponseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseTimeSpecified {
            get {
                return this.responseTimeFieldSpecified;
            }
            set {
                this.responseTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AttendeeAcceptEnum ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseTypeSpecified {
            get {
                return this.responseTypeFieldSpecified;
            }
            set {
                this.responseTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CounterProposeStartTime {
            get {
                return this.counterProposeStartTimeField;
            }
            set {
                this.counterProposeStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CounterProposeStartTimeSpecified {
            get {
                return this.counterProposeStartTimeFieldSpecified;
            }
            set {
                this.counterProposeStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CounterProposeEndTime {
            get {
                return this.counterProposeEndTimeField;
            }
            set {
                this.counterProposeEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CounterProposeEndTimeSpecified {
            get {
                return this.counterProposeEndTimeFieldSpecified;
            }
            set {
                this.counterProposeEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CounterProposeLocation {
            get {
                return this.counterProposeLocationField;
            }
            set {
                this.counterProposeLocationField = value;
            }
        }
        
        /// <remarks/>
        public LongText ResponseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
            }
        }
        
        /// <remarks/>
        public UserReference DelegateResponder {
            get {
                return this.delegateResponderField;
            }
            set {
                this.delegateResponderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttendeeEventExtraBlueType : AttendeeEventExtraType {
        
        private string changeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentMetadataBlueType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttachmentMetadataType {
        
        private LocalizableString nameField;
        
        private string contentTypeField;
        
        private string contentTransferEncodingField;
        
        private ulong sizeField;
        
        private byte[] attachmentBodyField;
        
        /// <remarks/>
        public LocalizableString Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ContentTransferEncoding {
            get {
                return this.contentTransferEncodingField;
            }
            set {
                this.contentTransferEncodingField = value;
            }
        }
        
        /// <remarks/>
        public ulong Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] AttachmentBody {
            get {
                return this.attachmentBodyField;
            }
            set {
                this.attachmentBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class AttachmentMetadataBlueType : AttachmentMetadataType {
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(YearlyByDayType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class WeekDayAttributesType {
        
        private bool suField;
        
        private bool suFieldSpecified;
        
        private bool moField;
        
        private bool moFieldSpecified;
        
        private bool tuField;
        
        private bool tuFieldSpecified;
        
        private bool weField;
        
        private bool weFieldSpecified;
        
        private bool thField;
        
        private bool thFieldSpecified;
        
        private bool frField;
        
        private bool frFieldSpecified;
        
        private bool saField;
        
        private bool saFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Su {
            get {
                return this.suField;
            }
            set {
                this.suField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuSpecified {
            get {
                return this.suFieldSpecified;
            }
            set {
                this.suFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Mo {
            get {
                return this.moField;
            }
            set {
                this.moField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoSpecified {
            get {
                return this.moFieldSpecified;
            }
            set {
                this.moFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Tu {
            get {
                return this.tuField;
            }
            set {
                this.tuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TuSpecified {
            get {
                return this.tuFieldSpecified;
            }
            set {
                this.tuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool We {
            get {
                return this.weField;
            }
            set {
                this.weField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeSpecified {
            get {
                return this.weFieldSpecified;
            }
            set {
                this.weFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Th {
            get {
                return this.thField;
            }
            set {
                this.thField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThSpecified {
            get {
                return this.thFieldSpecified;
            }
            set {
                this.thFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Fr {
            get {
                return this.frField;
            }
            set {
                this.frField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrSpecified {
            get {
                return this.frFieldSpecified;
            }
            set {
                this.frFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Sa {
            get {
                return this.saField;
            }
            set {
                this.saField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaSpecified {
            get {
                return this.saFieldSpecified;
            }
            set {
                this.saFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class YearlyByDayType : WeekDayAttributesType {
        
        private int yearFrequencyField;
        
        private bool yearFrequencyFieldSpecified;
        
        private WeekdayOfMonthEnum weekdayOfMonthField;
        
        private int monthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int YearFrequency {
            get {
                return this.yearFrequencyField;
            }
            set {
                this.yearFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearFrequencySpecified {
            get {
                return this.yearFrequencyFieldSpecified;
            }
            set {
                this.yearFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeekdayOfMonthEnum WeekdayOfMonth {
            get {
                return this.weekdayOfMonthField;
            }
            set {
                this.weekdayOfMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum WeekdayOfMonthEnum {
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        Second,
        
        /// <remarks/>
        Third,
        
        /// <remarks/>
        Fourth,
        
        /// <remarks/>
        Last,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleType {
        
        private RepeatRuleTypeDaily dailyField;
        
        private RepeatRuleTypeWeekly weeklyField;
        
        private RepeatRuleTypeMonthlyByDay monthlyByDayField;
        
        private RepeatRuleTypeMonthly monthlyField;
        
        private YearlyByDayType yearlyByDayField;
        
        private RepeatRuleTypeYearly yearlyField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public RepeatRuleTypeDaily Daily {
            get {
                return this.dailyField;
            }
            set {
                this.dailyField = value;
            }
        }
        
        /// <remarks/>
        public RepeatRuleTypeWeekly Weekly {
            get {
                return this.weeklyField;
            }
            set {
                this.weeklyField = value;
            }
        }
        
        /// <remarks/>
        public RepeatRuleTypeMonthlyByDay MonthlyByDay {
            get {
                return this.monthlyByDayField;
            }
            set {
                this.monthlyByDayField = value;
            }
        }
        
        /// <remarks/>
        public RepeatRuleTypeMonthly Monthly {
            get {
                return this.monthlyField;
            }
            set {
                this.monthlyField = value;
            }
        }
        
        /// <remarks/>
        public YearlyByDayType YearlyByDay {
            get {
                return this.yearlyByDayField;
            }
            set {
                this.yearlyByDayField = value;
            }
        }
        
        /// <remarks/>
        public RepeatRuleTypeYearly Yearly {
            get {
                return this.yearlyField;
            }
            set {
                this.yearlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleTypeDaily {
        
        private int dayFrequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DayFrequency {
            get {
                return this.dayFrequencyField;
            }
            set {
                this.dayFrequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleTypeWeekly : WeekDayAttributesType {
        
        private int weekFrequencyField;
        
        private bool weekFrequencyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int WeekFrequency {
            get {
                return this.weekFrequencyField;
            }
            set {
                this.weekFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeekFrequencySpecified {
            get {
                return this.weekFrequencyFieldSpecified;
            }
            set {
                this.weekFrequencyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleTypeMonthlyByDay : WeekDayAttributesType {
        
        private int monthFrequencyField;
        
        private bool monthFrequencyFieldSpecified;
        
        private WeekdayOfMonthEnum weekdayOfMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MonthFrequency {
            get {
                return this.monthFrequencyField;
            }
            set {
                this.monthFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonthFrequencySpecified {
            get {
                return this.monthFrequencyFieldSpecified;
            }
            set {
                this.monthFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeekdayOfMonthEnum WeekdayOfMonth {
            get {
                return this.weekdayOfMonthField;
            }
            set {
                this.weekdayOfMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleTypeMonthly {
        
        private int monthFrequencyField;
        
        private bool monthFrequencyFieldSpecified;
        
        private int dayField;
        
        private bool forceExactField;
        
        private bool forceExactFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MonthFrequency {
            get {
                return this.monthFrequencyField;
            }
            set {
                this.monthFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonthFrequencySpecified {
            get {
                return this.monthFrequencyFieldSpecified;
            }
            set {
                this.monthFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ForceExact {
            get {
                return this.forceExactField;
            }
            set {
                this.forceExactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceExactSpecified {
            get {
                return this.forceExactFieldSpecified;
            }
            set {
                this.forceExactFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RepeatRuleTypeYearly {
        
        private int yearFrequencyField;
        
        private bool yearFrequencyFieldSpecified;
        
        private int monthField;
        
        private int dayField;
        
        private bool forceExactField;
        
        private bool forceExactFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int YearFrequency {
            get {
                return this.yearFrequencyField;
            }
            set {
                this.yearFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearFrequencySpecified {
            get {
                return this.yearFrequencyFieldSpecified;
            }
            set {
                this.yearFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ForceExact {
            get {
                return this.forceExactField;
            }
            set {
                this.forceExactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceExactSpecified {
            get {
                return this.forceExactFieldSpecified;
            }
            set {
                this.forceExactFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecurrenceRuleBodyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecurrenceRuleType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RecurrenceRuleBodyBaseType {
        
        private System.DateTime creationDateField;
        
        private DayOfWeekEnum firstDayOfWeekField;
        
        private int tzidField;
        
        private bool tzidFieldSpecified;
        
        private bool isLeapYearField;
        
        private bool isLeapYearFieldSpecified;
        
        private int leapMonthValueField;
        
        private bool leapMonthValueFieldSpecified;
        
        private RepeatRuleType repeatField;
        
        private System.DateTime windowEndField;
        
        private bool windowEndFieldSpecified;
        
        private bool repeatForeverField;
        
        private bool repeatForeverFieldSpecified;
        
        private int repeatInstancesField;
        
        private bool repeatInstancesFieldSpecified;
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        public DayOfWeekEnum FirstDayOfWeek {
            get {
                return this.firstDayOfWeekField;
            }
            set {
                this.firstDayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        public int Tzid {
            get {
                return this.tzidField;
            }
            set {
                this.tzidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TzidSpecified {
            get {
                return this.tzidFieldSpecified;
            }
            set {
                this.tzidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsLeapYear {
            get {
                return this.isLeapYearField;
            }
            set {
                this.isLeapYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsLeapYearSpecified {
            get {
                return this.isLeapYearFieldSpecified;
            }
            set {
                this.isLeapYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int LeapMonthValue {
            get {
                return this.leapMonthValueField;
            }
            set {
                this.leapMonthValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeapMonthValueSpecified {
            get {
                return this.leapMonthValueFieldSpecified;
            }
            set {
                this.leapMonthValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RepeatRuleType Repeat {
            get {
                return this.repeatField;
            }
            set {
                this.repeatField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WindowEnd {
            get {
                return this.windowEndField;
            }
            set {
                this.windowEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WindowEndSpecified {
            get {
                return this.windowEndFieldSpecified;
            }
            set {
                this.windowEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RepeatForever {
            get {
                return this.repeatForeverField;
            }
            set {
                this.repeatForeverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepeatForeverSpecified {
            get {
                return this.repeatForeverFieldSpecified;
            }
            set {
                this.repeatForeverFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int RepeatInstances {
            get {
                return this.repeatInstancesField;
            }
            set {
                this.repeatInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepeatInstancesSpecified {
            get {
                return this.repeatInstancesFieldSpecified;
            }
            set {
                this.repeatInstancesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum DayOfWeekEnum {
        
        /// <remarks/>
        Su,
        
        /// <remarks/>
        Mo,
        
        /// <remarks/>
        Tu,
        
        /// <remarks/>
        We,
        
        /// <remarks/>
        Th,
        
        /// <remarks/>
        Fr,
        
        /// <remarks/>
        Sa,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecurrenceRuleType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RecurrenceRuleBodyType : RecurrenceRuleBodyBaseType {
        
        private System.DateTime[] deletedExceptionDateField;
        
        private string changeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeletedExceptionDate")]
        public System.DateTime[] DeletedExceptionDate {
            get {
                return this.deletedExceptionDateField;
            }
            set {
                this.deletedExceptionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RecurrenceRuleType : RecurrenceRuleBodyType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class RecurrenceType {
        
        private RecurrenceRuleType ruleField;
        
        private ModifiedExceptionType[] exceptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string changeNumberField;
        
        /// <remarks/>
        public RecurrenceRuleType Rule {
            get {
                return this.ruleField;
            }
            set {
                this.ruleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception")]
        public ModifiedExceptionType[] Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReminderBlueType))]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class ReminderType {
        
        private bool setField;
        
        private LocalizableString toField;
        
        private int offsetField;
        
        private int interruptabilityField;
        
        private bool interruptabilityFieldSpecified;
        
        private System.DateTime lastSentTimeField;
        
        private System.DateTime nextTriggerTimeField;
        
        /// <remarks/>
        public bool Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        public LocalizableString To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public int Interruptability {
            get {
                return this.interruptabilityField;
            }
            set {
                this.interruptabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InterruptabilitySpecified {
            get {
                return this.interruptabilityFieldSpecified;
            }
            set {
                this.interruptabilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastSentTime {
            get {
                return this.lastSentTimeField;
            }
            set {
                this.lastSentTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NextTriggerTime {
            get {
                return this.nextTriggerTimeField;
            }
            set {
                this.nextTriggerTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public partial class ReminderBlueType : ReminderType {
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum MeetingStatusEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not-sent")]
        Notsent,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqCalendar")]
    public enum CalendarLocaleEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item111,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
    }
}
