//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50215.44.
// 
namespace Commanigy.Iquomi.Services.IqPresence {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqPresence")]
    [System.Xml.Serialization.XmlRootAttribute("IqPresence", Namespace="http://schemas.iquomi.com/2004/01/iqPresence", IsNullable=false)]
    public partial class IqPresenceType {
        
        private EndpointType[] endpointField;
        
        private SubscriptionType[] subscriptionField;
        
        private string changeNumberField;
        
        private string instanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Endpoint")]
        public EndpointType[] Endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subscription")]
        public SubscriptionType[] Subscription {
            get {
                return this.subscriptionField;
            }
            set {
                this.subscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string InstanceId {
            get {
                return this.instanceIdField;
            }
            set {
                this.instanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqPresence")]
    public partial class EndpointType {
        
        private string deviceUuidField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private ArgotType[] argotField;
        
        private string nameField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public string DeviceUuid {
            get {
                return this.deviceUuidField;
            }
            set {
                this.deviceUuidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Argot")]
        public ArgotType[] Argot {
            get {
                return this.argotField;
            }
            set {
                this.argotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqPresence")]
    public partial class ArgotType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string argotURIField;
        
        private string nameField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ArgotURI {
            get {
                return this.argotURIField;
            }
            set {
                this.argotURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.iquomi.com/2004/01/core", DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class RoutingType {
        
        private string timestampField;
        
        private string hopsField;
        
        /// <remarks/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string Hops {
            get {
                return this.hopsField;
            }
            set {
                this.hopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ToType {
        
        private string originalUserField;
        
        /// <remarks/>
        public string OriginalUser {
            get {
                return this.originalUserField;
            }
            set {
                this.originalUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class CategoryType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class ExpiresType {
        
        private string ttlField;
        
        private string onDateField;
        
        private string replaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OnDate {
            get {
                return this.onDateField;
            }
            set {
                this.onDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class IdentityHeaderType {
        
        private string onBehalfOfUserField;
        
        private string licenseHolderField;
        
        private string platformIdField;
        
        private string typeField;
        
        /// <remarks/>
        public string OnBehalfOfUser {
            get {
                return this.onBehalfOfUserField;
            }
            set {
                this.onBehalfOfUserField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseHolder {
            get {
                return this.licenseHolderField;
            }
            set {
                this.licenseHolderField = value;
            }
        }
        
        /// <remarks/>
        public string PlatformId {
            get {
                return this.platformIdField;
            }
            set {
                this.platformIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class FromType {
        
        private IdentityHeaderType identityHeaderField;
        
        private ExpiresType expiresAtField;
        
        private string acknowledgeField;
        
        private CategoryType categoryField;
        
        /// <remarks/>
        public IdentityHeaderType IdentityHeader {
            get {
                return this.identityHeaderField;
            }
            set {
                this.identityHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ExpiresType ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        public string Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public CategoryType Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class NotificationType {
        
        private FromType fromField;
        
        private ToType toField;
        
        private NotificationTypeContents contentsField;
        
        private RoutingType routingField;
        
        private string idField;
        
        /// <remarks/>
        public FromType From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public ToType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public NotificationTypeContents Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        public RoutingType Routing {
            get {
                return this.routingField;
            }
            set {
                this.routingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqAlerts")]
    public partial class NotificationTypeContents {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionType {
        
        private SubscriptionTypeTrigger triggerField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private SubscriptionTypeContext contextField;
        
        private string toField;
        
        private string changeNumberField;
        
        private string idField;
        
        private byte[] creatorField;
        
        /// <remarks/>
        public SubscriptionTypeTrigger Trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionTypeContext Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="hexBinary")]
        public byte[] Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeTrigger {
        
        private string selectField;
        
        private SubscriptionTypeTriggerMode modeField;
        
        private string baseChangeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Select {
            get {
                return this.selectField;
            }
            set {
                this.selectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public SubscriptionTypeTriggerMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="nonNegativeInteger")]
        public string BaseChangeNumber {
            get {
                return this.baseChangeNumberField;
            }
            set {
                this.baseChangeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public enum SubscriptionTypeTriggerMode {
        
        /// <remarks/>
        IncludeData,
        
        /// <remarks/>
        ExcludeData,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/core")]
    public partial class SubscriptionTypeContext {
        
        private System.Xml.XmlElement[] anyField;
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.iquomi.com/2004/01/iqPresence")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqPresence", IsNullable=false)]
    public partial class NotifyEndpointRequest {
        
        private string endpointIdField;
        
        private NotificationType notificationField;
        
        /// <remarks/>
        public string EndpointId {
            get {
                return this.endpointIdField;
            }
            set {
                this.endpointIdField = value;
            }
        }
        
        /// <remarks/>
        public NotificationType Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
    }
}
