//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50215.44.
// 
namespace Commanigy.Iquomi.Services.IqAlerts {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Notify", Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd", IsNullable=false)]
    public partial class NotifyType {
        
        private ViewType contentField;
        
        private string languageField;
        
        private MetaType metaField;
        
        /// <remarks/>
        public ViewType Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public MetaType Meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd")]
    public partial class ViewType {
        
        private string contentTypeField;
        
        private string deviceHintField;
        
        private string subjectField;
        
        private string valueField;
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceHint {
            get {
                return this.deviceHintField;
            }
            set {
                this.deviceHintField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd")]
    public partial class MetaType {
        
        private string actionUrlField;
        
        private string baseUrlField;
        
        private string iconUrlField;
        
        private string subjectField;
        
        private string subscriptionUrlField;
        
        /// <remarks/>
        public string ActionUrl {
            get {
                return this.actionUrlField;
            }
            set {
                this.actionUrlField = value;
            }
        }
        
        /// <remarks/>
        public string BaseUrl {
            get {
                return this.baseUrlField;
            }
            set {
                this.baseUrlField = value;
            }
        }
        
        /// <remarks/>
        public string IconUrl {
            get {
                return this.iconUrlField;
            }
            set {
                this.iconUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionUrl {
            get {
                return this.subscriptionUrlField;
            }
            set {
                this.subscriptionUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("NotifyResponse", Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd", IsNullable=false)]
    public partial class NotifyResponseType {
        
        private ResponseStatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResponseStatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.iquomi.com/2004/01/iqAlerts/Notify.xsd")]
    public enum ResponseStatusType {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Rollback,
        
        /// <remarks/>
        NotAttempted,
    }
}
